### ISSUE TITLE
The purpose of zk-Keeper module

### ISSUE THREAD

**Issue by imesh** [gsjurseth/opdk4k8s#2]
This is to clarify the purpose of zk-Keeper module. The `ds.yaml` file currently execute the below command on the container startup and it seems to be restarting `apigee-zookeeper` service in other containers:
```
sudo HOSTIP=\"$(hostname).dshs.default.svc.cluster.local\" 
/opt/apigee/apigee-setup/bin/setup.sh -p ds -f /config/opdk.config && 
(for a in $(echo -e \"ds-0.dshs\nds-1.dshs\nds-2.dshs\" | fgrep -v $(hostname)); 
do 
    echo \"trying $a\" ; 
    curl -s -X POST http://$a:9999/zk ; 
done ; 
exit 0) && 
/localdaemon/zk-Keeper
```

Would you mind clarifying the reasons behind?

**Comment by gsjurseth** [comment]
Exactly what it does
That way the others become aware of the new IP when one of them starts up
